draupnir:
  image:
    repository: gnuxie/draupnir
    tag: v2.8.0@sha256:d8029f32a7b9c1bbef2b3b8b12b9a682b18a3fc1a6e5505d9072a5295a08e255

frigate:
  image:
    registry: ghcr.io
    repository: blakeblackshear/frigate
    tag: stable@sha256:cb6624b9075f76ece626139eedca7e728cab1456a5f8c351afbf877320826bc1

ovenmediaengine:
  image:
    repository: airensoft/ovenmediaengine
    tag: v0.19.0@sha256:6d91bd9b97a625ba9f03e7efc42d6f90928473d612569a7d48ef53d4be274fc7
