draupnir:
  image:
    repository: gnuxie/draupnir
    tag: v2.7.1@sha256:b1f5df236de3c0f83621f95ae17e3944d897c44adde7ed5fe045c685290eabc1

frigate:
  image:
    registry: ghcr.io
    repository: blakeblackshear/frigate
    tag: stable@sha256:cb6624b9075f76ece626139eedca7e728cab1456a5f8c351afbf877320826bc1

home-assistant:
  image:
    registry: ghcr.io
    repository: home-assistant/home-assistant
    tag: 2025.11.1@sha256:c11dd7c74039223c43079d700aa559d6dc61e8e0b38a08d651f91d1bc550cff5

ovenmediaengine:
  image:
    repository: airensoft/ovenmediaengine
    tag: v0.19.0@sha256:6d91bd9b97a625ba9f03e7efc42d6f90928473d612569a7d48ef53d4be274fc7
